version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    working_dir: /app
    environment:
      - PYTHONPATH=/app/cats
      - DJANGO_SETTINGS_MODULE=kittygram_backend.settings
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    build: ./gateway/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static_volume:/static
      - media_volume:/app/media

